spring:
  application:
    name: transaction-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-nn9c6m8o.us.auth0.com/
server:
  port: 8082
auth0:
  audience: https://dev-nn9c6m8o.us.auth0.com/api/v2/
